# Generated by Django 2.2.10 on 2020-04-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='color',
            field=models.TextField(default='#000000'),
        ),
        migrations.AlterField(
            model_name='state',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
