# Generated by Django 2.2.10 on 2020-04-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0002_auto_20200405_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='state',
            name='color',
            field=models.CharField(default='#000000', max_length=250),
        ),
    ]
