# Generated by Django 2.1.15 on 2020-05-01 12:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, null=True)),
                ('description', models.TextField(blank=True)),
                ('path', models.CharField(default='D:/git5/zagent/executor.bat', max_length=250)),
                ('script_content', models.TextField(default='call "test.bat"')),
                ('script_inputs', models.CharField(default='Y', max_length=250)),
                ('delay', models.IntegerField(default=30)),
                ('output', models.TextField(blank=True)),
                ('result', models.CharField(default='0', max_length=1)),
                ('start_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('is_scheduled', models.CharField(default='0', max_length=1)),
                ('is_deleted', models.CharField(default='0', max_length=1)),
            ],
        ),
    ]
