# Generated by Django 2.1.15 on 2020-04-26 17:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='is_scheduled',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='agent',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='result',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
