# Generated by Django 2.1.15 on 2020-05-01 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='path',
            field=models.CharField(default='executor.bat', max_length=250),
        ),
    ]
