# Generated by Django 2.1.15 on 2020-04-26 17:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_auto_20200426_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='start_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
