# Generated by Django 2.2.10 on 2020-04-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='bcclist',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='mail',
            name='cclist',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='mail',
            name='tolist',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
