# Generated by Django 2.1.15 on 2020-05-01 12:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('smtp', models.CharField(max_length=250)),
                ('port', models.CharField(max_length=250)),
                ('username', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
                ('tolist', models.CharField(blank=True, max_length=250, null=True)),
                ('cclist', models.CharField(blank=True, max_length=250, null=True)),
                ('bcclist', models.CharField(blank=True, max_length=250, null=True)),
                ('btype', models.CharField(max_length=250, null=True)),
                ('priority', models.CharField(max_length=250, null=True)),
                ('state', models.CharField(max_length=250, null=True)),
                ('color', models.CharField(default='#000000', max_length=250)),
                ('created_by', models.CharField(max_length=250, null=True)),
                ('code', models.CharField(max_length=250, null=True)),
                ('title', models.CharField(max_length=250, null=True)),
                ('detail', models.TextField(null=True)),
                ('effect', models.TextField(null=True)),
                ('contact', models.TextField(null=True)),
                ('begin_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('duration', models.IntegerField(default='0')),
                ('ticket_case_url', models.CharField(blank=True, default='#', max_length=250)),
                ('ticket_case_id', models.CharField(blank=True, max_length=250, null=True)),
                ('resolved_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('is_resolved', models.CharField(default='0', max_length=1)),
                ('resolved_by', models.CharField(blank=True, max_length=250, null=True)),
                ('temporary_solution', models.TextField(blank=True, null=True)),
                ('permanent_solution', models.TextField(blank=True, null=True)),
                ('root_cause', models.TextField(blank=True, null=True)),
                ('insert_time', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('modify_time', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('is_automated', models.CharField(default='0', max_length=1)),
                ('is_deleted', models.CharField(default='0', max_length=1)),
            ],
        ),
    ]
