# Generated by Django 2.2.10 on 2020-04-05 12:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletin',
            name='bcclist',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='bulletin',
            name='cclist',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='bulletin',
            name='end_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='bulletin',
            name='permanent_solution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bulletin',
            name='resolved_by',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='bulletin',
            name='resolved_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='bulletin',
            name='root_cause',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bulletin',
            name='temporary_solution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bulletin',
            name='ticket_case_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='bulletin',
            name='tolist',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
