# Generated by Django 2.1.15 on 2020-04-25 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletin',
            name='is_automated',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='bulletin',
            name='ticket_case_url',
            field=models.CharField(blank=True, default='#', max_length=250),
        ),
    ]
