# Generated by Django 2.2.10 on 2020-04-05 07:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0002_auto_20200404_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulletin',
            name='content',
        ),
        migrations.AddField(
            model_name='bulletin',
            name='begin_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='btype',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='code',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='color',
            field=models.CharField(default='#000000', max_length=250),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='contact',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='created_by',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='detail',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='duration',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='effect',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='insert_time',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='is_deleted',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='is_resolved',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='modify_time',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='permanent_solution',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='priority',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='resolved_by',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='resolved_time',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='root_cause',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='state',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='temporary_solution',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='ticket_case_id',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='ticket_case_url',
            field=models.CharField(default='#', max_length=250),
        ),
        migrations.AlterField(
            model_name='bulletin',
            name='title',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
