# Generated by Django 2.2.10 on 2020-04-04 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('btypes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='BType',
        ),
    ]
